from datetime import datetime

class ReportNarrator:
    def write_report(self, bug):
        timestamp = int(datetime.now().timestamp())
        filename = f"reports/active/P{bug['severity_score']}_{bug['title'].replace(' ', '_')}_{timestamp}.md"
        
        content = f"""
# 🚨 {bug['title']}

**Severity:** {bug['severity_label']} (P{bug['severity_score']})
**Status:** CONFIRMED (Confidence: {bug['confidence']}%)
**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

---

## ❓ Bug kya hai? (Simple Explanation)
{bug['simple_explanation']}

## 📍 Bug kaha hai?
- **URL:** `{bug['url']}`
- **Parameter:** `{bug['param']}`
- **Logic:** {bug['logic_type']}

## ⚙️ Technical Proof (Step-by-Step)
1. **User A** (Attacker) sends request to `{bug['url']}`.
2. **User A** swaps ID to `{bug['victim_id']}`.
3. **Server** responds with `200 OK` and Body Length `{bug['response_len']}`.
4. **AI Critique:** "Data contains PII (Email/Phone) of User B."

## 📉 Business Impact
{bug['business_impact']}

## 🛡️ Fix Recommendation
{bug['fix']}

---
*Generated by TITAN OMEGA v∞⁸ (Human-Grade Logic Hunter)*
"""
        with open(filename, "w") as f:
            f.write(content)
        return filename
      
